### ISSUE TITLE
Use spawn instead of exec

### ISSUE THREAD

**Issue by xBajci** [neekey/ps#37]
Hi, 
I was debugging my app and found out that I run lot of processes on my pc and the output from `ps -A` exceeded 200kB, which is default buffer size for `child_process.exec` function, and then child process was killed.  I was wondering why not to use `child_process.spawn` when it is already used for `win` branch.

I saw it as change to contribute to open sourced package I use and tried to implement it using `spawn` and it worked or at least it helped to solve my problem. Here's pull request in my forked version [Use spawn instead of exec](https://github.com/xBajci/ps/pull/1).

While it works 'on my machine', it randomly fails with different node versions on travis. Have no idea why. I tested it with more node versions on my machine and it still worked. 

So, is there any particular reason to not use `child_process.spawn` ?  Do you have any idea what could be the issue with my solution? 

PS. Increasing buffer size for `exec` could also help, but I'm not fun of such solutions.

Martin

**Comment by neekey** [comment]
Hi, thanks for submitting this issue and I think it's quite necessary to use spawn instead of exec to avoid the `Error: maxBuffer exceeded` error.

Can you please take a simple review of the PR? https://github.com/neekey/ps/pull/40

**Comment by neekey** [comment]
Already merged
