### ISSUE TITLE
Use process.kill on UNIX

### ISSUE THREAD

**Issue by honzajavorek** [neekey/ps#41]
If I see correctly, the code for killing processes calls `kill` as a subprocess on UNIX. Is there a reason to do so? Why not to use built-in [`process.kill()`](https://nodejs.org/api/process.html#process_process_kill_pid_signal)?

**Comment by neekey** [comment]
@honzajavorek thanks for pointing this out, I don't think there's a reason to do so Lol, I must did think it through at that time.

I will consider replacing it will the build-in version.
