### ISSUE TITLE
Show all processes in ubuntu.

### ISSUE THREAD

**Issue by legobit** [neekey/ps#47]
exports.lookup = function (query, callback) {
-line  var exeArgs = query.psargs || ['l'];
+line  var exeArgs = query.psargs || ['lx'];

Without the x only processes with a tty will show.

**Comment by neekey** [comment]
will update in the next release, you can use the option `psargs` to change the option for the moment

**Comment by neekey** [comment]
0.1.6 released https://github.com/neekey/ps/pull/48
