### ISSUE TITLE
Can't get results from some searches

### ISSUE THREAD

**Issue by kingio** [neekey/ps#61]
Hi, this is more a problem making the search than a bug:
**O.S:** Lubuntu
**Node version:** 6.11.0
**ps version:** 0.1.6

```js
ps.lookup({
        command: "chromium-browser"
    }, function(err, resultList) {
   console.log(resultList.length);
});
```

I get 0. If i run `ps -C chromium-browser` i do get results:
```
osboxes@osboxes:~$ ps -C chromium-browser
  PID TTY          TIME CMD
 1979 ?        00:23:34 chromium-browse
 1987 ?        00:00:00 chromium-browse
 1989 ?        00:00:00 chromium-browse
 2450 ?        00:00:03 chromium-browse
 2470 ?        00:03:02 chromium-browse
 2483 ?        00:00:40 chromium-browse
 3490 ?        00:00:02 chromium-browse
 3492 ?        00:00:00 chromium-browse
 5775 pts/0    00:00:01 chromium-browse
 5784 pts/0    00:00:00 chromium-browse
 5786 pts/0    00:00:00 chromium-browse
```

If i search for `node` i do get results.

¿What commad does exactly ps run?

**Comment by neekey** [comment]
Hi @kingio, you can take a look at the documentation [here}(https://github.com/neekey/ps#how-does-it-work)

> Linux / Mac: use ps command. Since the default result from shell command $ ps will not contain "command arguments" in linux like "ubuntu", ps-node add arguments lx as default. Which means, the default value for option psargs is lx.
